name: Upload to Official Plugin Repository Fork

on:
  push:
    tags:
      - '*'

env:
  SOLUTION_NAME: ARealmRecorded
  INTERNAL_NAME: ARealmRecorded
  EXTERNAL_NAME: A Realm Recorded
  RELEASE_DIR: ./Publish
  PLUGIN_REPO_FORK: UnknownX7/DalamudPlugins
  PLUGIN_REPO_BRANCH: api6

jobs:
  build:
    runs-on: [windows-2022]

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet Packages
        run: nuget restore ${{ env.SOLUTION_NAME }}.sln

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build
        run: msbuild ${{ env.SOLUTION_NAME }}.sln /p:Configuration=Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          path: ${{ env.RELEASE_DIR }}/*

  deploy:
    needs: build
    runs-on: [ubuntu-latest]

    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - uses: actions/checkout@v2
      with:
        repository: ${{ env.PLUGIN_REPO_FORK }}
        ref: ${{ env.PLUGIN_REPO_BRANCH }}
        token: ${{ secrets.PAT }}

    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: testing/${{ env.INTERNAL_NAME }}

    - uses: EndBug/add-and-commit@v7
      with:
        add: --all
        branch: ${{ env.PLUGIN_REPO_BRANCH }}
        message: '[Testing] ${{ env.EXTERNAL_NAME }} ${{ steps.get_version.outputs.VERSION }}'
